services:
  marzinefrontend:
    image: docker.marclev.com/dfactory/marzineofffrontend:v0.1.15
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5174:5174
